### ISSUE TITLE
Plan for clickable edges

### ISSUE THREAD

**Issue by Schabolon** [blitzarx1/egui_graphs#100]
Hi,

I wanted to ask whether you plan on making edges clickable in the same way as nodes are clickable.
I am quite new to rust, but in case you haven't implemented the feature yourself, I could try to create a pull request implementing the feature.

**Comment by blitzarx1** [comment]
Yep I thought about it. I think for the moment you can try to implement it in `FnCustomEdgeDraw` where you can register event of clicking on edge and changing its color. I will think in parallel how to implement it in lib. 

The only thing which can be non trivial is that edges in the lib are not always straight lines. When you have multiple edges between two nodes they are drawn curved and it becomes not easy to register click on a curved node. But I ll try to figure a way.

**Comment by blitzarx1** [comment]
If you wish you can try pr if you manage to solve the problem which I mentioned.

**Comment by blitzarx1** [comment]
Solved. Thanks @Schabolon
