### ISSUE TITLE
Non-standard Index size

### ISSUE THREAD

**Issue by dmyyy** [blitzarx1/egui_graphs#102]
Graph can only be created w/ the standard DefaultIx size (u32). It would be nice if it was generic over different index sizes so it can support any petgraph stable graph. I can help make this change.

**Comment by blitzarx1** [comment]
Thanks for the feedback. Sounds good to me. Please file a PR. I am glad to new contributions which expand number of usecases for the project.

**Comment by dmyyy** [comment]
https://github.com/blitzarx1/egui_graphs/pull/103

**Comment by blitzarx1** [comment]
Thank you for the contribution. Waiting for https://github.com/blitzarx1/egui_graphs/issues/100 and packing new release!
