### ISSUE TITLE
Problem with curved edges selection

### ISSUE THREAD

**Issue by blitzarx1** [blitzarx1/egui_graphs#109]
This effect is reproducable when you have an edge with big curvature (multiple duplicate edges and nodes are close together). 

When the curvature is big enough you can click 'below' the edge (opposite to curvature direction) and edge will still be selected. Moreover clicking directly on the edge might not select it. It feels like selection area has less curvature than the edge itself.

**Comment by blitzarx1** [comment]
@Schabolon  as original creator of the feature you could take this for further investigation if you wish.

**Comment by Schabolon** [comment]
Sure, I can take a look at it :+1:
