### ISSUE TITLE
Why are Node and NodeShape separate?

### ISSUE THREAD

**Issue by patrik-cihal** [blitzarx1/egui_graphs#122]
I don't really see a reason to separate them. But many reasons for not doing so.

**Comment by patrik-cihal** [comment]
For instance, I find it impossible to implement adjusting node shape based on the width of text inside. But that will require also some other API changes I think.

**Comment by blitzarx1** [comment]
Node stores data regarding node in the graph, like selection or dragged state and position. While NodeShape stores data relevant to visualization of the node. We can discuss it in more details if you show an example where this design fails and other turns to be beneficial.

**Comment by patrik-cihal** [comment]
For instance, implementing the rect size based on the text inside, proved to be very difficult. Also what if I want to make the node animated, the fact that the Node Shape is newly instantiated whenever a new draw function is called makes this impossible...

**Comment by blitzarx1** [comment]
Yes, now I get your point. Actually I am planning to implement it as well. This is just first version.
