### ISSUE TITLE
Examples throw FnMut error

### ISSUE THREAD

**Issue by cds-internationalist** [blitzarx1/egui_graphs#161]
The following error is thrown when trying to run examples;

**expected a 'FnMut(&mut Ui)' closure, found 'GraphView<'_, (), ()>**

On lines in the update function where we ui.add(&mut GraphView::<...

**Comment by blitzarx1** [comment]
what example have you tried to run?

**Comment by cds-internationalist** [comment]
Figured out my issue - error was behind the keyboard - I hadn't properly copied some of the "use" statements, so I was using petgraph::graph::Graph instead of egui_graphs::Graph
