### ISSUE TITLE
cannot be compiled without egui_persistence when egui is compiled with persistence

### ISSUE THREAD

**Issue by XertroV** [blitzarx1/egui_graphs#165]
this isn't too much of an issue i guess because not much is persisted, however, it does make #164 harder to debug. (I'm using the 'Reset egui' button from the demo backend panel to fix it; but not everyone will have that)

**Comment by blitzarx1** [comment]
Before going stable we will decide what goes into the default feature set. For the moment if you want to use persistence feature in egui you need to explicitly enable `egui_persistence` feature
