### ISSUE TITLE
middle clicking on a node will drag it instead of the viewport

### ISSUE THREAD

**Issue by XertroV** [blitzarx1/egui_graphs#167]
if you have a viewport you can drag with middle click (not sure if this is dependent on a specific option i have enabled), then middle clicking on the node will drag the node, which probably isn't what ppl expect. Right click does this too I think.

Notably, middle click and right click do not trigger the selected node event.

**Comment by blitzarx1** [comment]
Good point. I think we can make middle click only for moving viewport. And leave left and right click for interactions with graph elements.
