### ISSUE TITLE
unwrap panic when resizing an egui window over the top of a graph

### ISSUE THREAD

**Issue by XertroV** [blitzarx1/egui_graphs#169]
unwrap occurs here in graph_view.rs:
```rust
if resp.drag_started() {
    if let Some(idx) = self.g.node_by_screen_pos(meta, resp.hover_pos().unwrap()) {
        self.set_drag_start(idx);
    }
}
```

**Comment by blitzarx1** [comment]
I can't reproduce it. I resized it in configurable example and everything was fine. Could you please specify the conditions under which panic happens?

**Comment by blitzarx1** [comment]
Isn't #175 fixes it?
