### ISSUE TITLE
Add ability to remove nodes

### ISSUE THREAD

**Issue by XertroV** [blitzarx1/egui_graphs#176]
Removing nodes is currently broken atm if you add more nodes afterwards. 
This is probably because the indexes get out of sync between egui_graphs and petgraph.
You can observe the bug in the configurable example by reducing and then increasing the node count. Nodes end up looping back to themselves (which is the same behavior I see)

**Comment by blitzarx1** [comment]
You can check the flow in the **configurable**. 
I agree that it is far from ideal, and I have plans to add addition and deletion of nodes to the graph API.

**Comment by blitzarx1** [comment]
improves #135
