### ISSUE TITLE
make SettingsStyle.labels_always public

### ISSUE THREAD

**Issue by nacl42** [blitzarx1/egui_graphs#202]
Refers to:  egui_graphs version: 0.21.1

I tried to implement my own NodeShape, using the given DefaultNodeShape as starting point.

The following line will not work in a new NodeShape object outside of the crate:

```
let label_visible = ctx.style.labels_always || self.selected || self.dragged;
```

I suggest to change the visibility of labels_always from `pub(crate)` to `pub` or alternatively add a getter method such as `fn labels_always(&self) -> bool` to SettingsStyle.

Everything else worked for my own custom NodeShape.

**Comment by blitzarx1** [comment]
`SettingsStyle` has `with_labels_always_method` which you can use to set `labels_always` property. It works the same as setters for other `Settings...` structs.

**Comment by blitzarx1** [comment]
@nacl42 please comment if this is solved?

**Comment by blitzarx1** [comment]
Closing it as everything seems to work...
