### ISSUE TITLE
add public exports required to implement DisplayEdge

### ISSUE THREAD

**Issue by nacl42** [blitzarx1/egui_graphs#203]
The DefaultDisplayEdge uses the two structs `EdgeShapeBuilder` and `TipProps` for drawing the edges.

When implementing a custom struct implementing the `DisplayEdge` trait from outside the crate, the two structs are not visible, even though they are declared public. The reason is that they are not publicly exported in the corresponding mod.rs and lib.rs files.

If requested, I could set up a pull request (once I figured out how to do this...), as I have fixed the problem in my local git repository.

**Comment by blitzarx1** [comment]
Hi, sorry for the long answer.

But actually you do not need this structs to implement `DisplayEdge` trait. This struct are used solely as helpers to construct `DefaultEdgeShape`.

**Comment by nacl42** [comment]
Your new example solved my issue by showing me a better way to implement custom edge drawing. Thanks!
