### ISSUE TITLE
Large graphs can crash egui

### ISSUE THREAD

**Issue by justinlovinger** [blitzarx1/egui_graphs#219]
The error is: `epaint-0.28.1/src/text/font.rs:92:9: assertion failed: scale_in_pixels > 0.0`. I am running into the error frequently with large force-directed graphs. Unfortunately, the nature of force-directed graphs means finding a minimal reproducible example is difficult. The error-message seems to provide enough of a hint though. I assume `scale_in_pixels` is getting rounded to `0` somewhere.

**Comment by blitzarx1** [comment]
Hi @justinlovinger I think I might have fixed it in #218. Will check after it is in main.
