### ISSUE TITLE
Running graph with zoom_and_pan option crashes windows when trying to zoom out

### ISSUE THREAD

**Issue by T1mo7hy** [blitzarx1/egui_graphs#50]
The nav settings used on the graph is:
```
SettingsNavigation {
    fit_to_screen: false,
    zoom_and_pan: true,
    zoom_step: 10.0,
    ..Default::default()
}
```

The panning works but when I try to zoom in/out I get an error:
thread 'main' panicked at 'Tried to allocate a 1870040320 wide glyph in a 8192 wide texture atlas', C:\Users\<folder>\.cargo\registry\src\github.com-1ecc6299db9ec823\epaint-0.22.0\src\texture_atlas.rs:200:9

**Comment by blitzarx1** [comment]
Thanks for the report. I have not tested this on windows, it should be covered by egui means. But I will check anyway.
