### ISSUE TITLE
Serde support

### ISSUE THREAD

**Issue by woelper** [blitzarx1/egui_graphs#90]
Hi, and thank you for this great library!

When I have the `persistence` feature enabled in egui, this crate fails to build with error messages like these:

```
error[E0277]: the trait bound `for<'a> metadata::Metadata: serde::de::Deserialize<'a>` is not satisfied
   --> .cargo/registry/src/index.crates.io-6f17d22bba15001f/egui_graphs-0.13.2/src/metadata.rs:33:47
    |
33  |             data.insert_persisted(Id::null(), self);
    |                  ----------------             ^^^^ the trait `for<'a> serde::de::Deserialize<'a>` is not implemented for `metadata::Metadata`
    |                  |
    |                  required by a bound introduced by this call
```

What do you think about adding serde support, perhaps behind a feature flag?

**Comment by blitzarx1** [comment]
Thanks for the comment. Definitely this case should be supported. I look into it asap.

**Comment by blitzarx1** [comment]
Releasing new version with this change. Made it under feature toggle. 

https://github.com/blitzarx1/egui_graphs#egui-features-support

**Comment by woelper** [comment]
Wow, you are both fast and awesome! Thanks!
