### ISSUE TITLE
Display lables at edges

### ISSUE THREAD

**Issue by Schabolon** [blitzarx1/egui_graphs#96]
Hi,

I couldn't find a way to display lables at edges and wanted to ask if I missed something or if this feature is planed in the future.

Thanks in advance and great project :+1:

**Comment by blitzarx1** [comment]
Thanks for the feedback! 

For the moment there is no such feature, **but** right now I am working on adding custom edge drawing functions and implementing an example with it where I add label to an edge. I think I will push it this weekend and you can use it for now. 

Later I will add the possibility to draw label for edge as a separate feature. I will prioritize it.

I ll leave this issue open and bind the incoming pr with example with custom edge drawing function.

**Comment by Schabolon** [comment]
Thank you for your fast response and for already working on it, really amazing!

**Comment by blitzarx1** [comment]
Ok, I've published a new release with custom edges drawing function and demo how to use it to draw labels for edges. https://github.com/blitzarx1/egui_graphs/releases/tag/v0.15.0

As for the edge labels as feature of the widget it is now planned to be in v1.0.0. I think in couple of week I'll ship it.

I'll keep this issue open till the feature is released. Thanks for using my lib and for the feedbacks!

**Comment by blitzarx1** [comment]
As #108 is done this can be easily implemented in `DisplayEdge` implementation.

**Comment by blitzarx1** [comment]
In master
