### ISSUE TITLE
Custom node draw with large nodes not clickable

### ISSUE THREAD

**Issue by Schabolon** [blitzarx1/egui_graphs#99]
When using `with_custom_node_draw()` for drawing rectangular (quite large) nodes with long text in it, the node is only clickable in the center. The outer part of the rect shape is not clickable and the edges start inside the rect:
![image](https://github.com/blitzarx1/egui_graphs/assets/31383697/2a3447e5-171b-4577-8363-afe5897c1ce7)

**Comment by blitzarx1** [comment]
Ok, this has 2 parts:
1. Node clickable in the center is a bug. I need to think about user implementing his own function `is_inside(pos: Vec2)` for custom drawn node, to check if cursor is inside node. And lib will use it to determine if click was inside, because now it does not account for custom node sizes
2. Second part can now be handled by custom edges drawing func. As when you draw custom node shape lib does not know where the bounds of the node and uses default round bounds. I will also think on this moment, but for now, you can handle it yourself in custom node drawing func.

**Comment by patrik-cihal** [comment]
I've forked it and already implemented "node_detect" and "with_custom_node_detect".

**Comment by blitzarx1** [comment]
@patrik-cihal you can always file a pull request if you wish.

Overall my idea of solving this bug is to oblige users of the lib to implement two apis for their custom nodes
```rust
/// returns if provided position is inside the node boundaries.
/// could be used for proper node clicking and selection.
fn is_inside(&self, pos: Pos2) -> bool

/// returns point which lies on the node boundary between its center and the provided `target`.
/// could be used to bind edge starts and tips for the custom drawn nodes.
fn boundary_intersection_point(&self, target: Pos2) -> Pos2
```

We can think of the names for the methods but the idea covers the fix.

**Comment by patrik-cihal** [comment]
As it's right now implemented, you'd need more to detect these things. Like Settings Style and Metadata.

This is my implementation for reference:
```rs
fn default_node_detect<N: Clone>(meta: &Metadata, n: &Node<N>, pos_in_graph: Vec2, settings_style: &SettingsStyle) -> bool {
    let dist_to_node = (n.location() - pos_in_graph).length();
    dist_to_node <= n.screen_radius(meta, &settings_style) / meta.zoom
}
```

**Comment by blitzarx1** [comment]
That is correct. I have the same in master
```rust 
    /// Finds node by position. Can be optimized by using a spatial index like quad-tree if needed.
    pub fn node_by_screen_pos(
        &self,
        meta: &'a Metadata,
        style: &'a SettingsStyle,
        screen_pos: Pos2,
    ) -> Option<(NodeIndex, &Node<N>)> {
        let pos_in_graph = (screen_pos.to_vec2() - meta.pan) / meta.zoom;
        self.nodes_iter().find(|(_, n)| {
            let dist_to_node = (n.location() - pos_in_graph).length();
            dist_to_node <= n.screen_radius(meta, style) / meta.zoom
        })
    }
 ```
 I 've edited my comment.
 
 Your implementation does not cover custom drawn nodes, which can be not round and which need their own implementation the api I shown.

**Comment by patrik-cihal** [comment]
No, this is just the default function, my implementation allows for adding your own custom node detect function. But maybe doing it through traits may be better, as you say.

**Comment by blitzarx1** [comment]
Ah, ok I see. Anyway, If you come to make a PR I would gladly explore your solution. For the moment I am planning to implement the one I've described.

**Comment by blitzarx1** [comment]
implementing in this pr https://github.com/blitzarx1/egui_graphs/pull/108

**Comment by blitzarx1** [comment]
The fix is in master along with the massive drawing updates. Please check `custom_draw` example for more info.
